- type: job
  id: EvolverPackFang
  name: job-evolver-fang
  icon: pack
  description: job-evolver-fang-desc
  playTimeTracker: JobEvolverPackFang
  whitelisted: true
  requirements:
    - !type:SpeciesRequirement
      species:
      - Moth
      - Diona
      - Arachnid
      - Reptilian
      - SlimePerson
      - Vox
  startingGear: STEvolverPackFangGear
  supervisors: job-evolver-fang-supervisor
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - EvolverPack
            - Evolver
        - type: Bands
          band: Evolver
          bandIcon: pack
          bandProto: STEvolversBand
          bandRankId: 2
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: STEvolverPackFangGear
  equipment:
    id: BandPDA
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat


- type: job
  id: EvolverPackAlpha
  name: job-evolver-alpha
  icon: pack
  description: job-evolver-alpha-desc
  playTimeTracker: JobEvolverPackAlpha
  whitelisted: true
  requirements:
    - !type:SpeciesRequirement
      species:
      - Moth
      - Diona
      - Arachnid
      - Reptilian
      - SlimePerson
      - Vox
  startingGear: STEvolverPackAlphaGear
  supervisors: job-evolver-alpha-supervisor
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Evolver
            - EvolverPack
        - type: Bands
          band: Evolver
          bandIcon: pack
          bandProto: STEvolversBand
          bandRankId: 4
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: STEvolverPackAlphaGear
  equipment:
    id: BandPDA
    neck: ClothingNeckDogtagBrigand
    eyes: ClothingEyesGlassesSunglasses
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat
