- type: playTimeTracker
  id: JobStalker

- type: playTimeTracker
  id: JobStalkerVeteran

- type: playTimeTracker
  id: JobTrader

- type: playTimeTracker
  id: JobMilitary

- type: playTimeTracker
  id: JobMilitaryStalker

- type: playTimeTracker
  id: JobBandit

- type: playTimeTracker
  id: JobPostulant

- type: playTimeTracker
  id: JobBishop

- type: playTimeTracker
  id: JobSeraphims

- type: playTimeTracker
  id: JobStalkerAnomalist

- type: playTimeTracker
  id: StalkerAnomalistGuardian

- type: playTimeTracker
  id: JobJournalist

- type: playTimeTracker
  id: JobNeutral

- type: playTimeTracker
  id: JobProjectPawn

- type: playTimeTracker
  id: JobProjectOrchestrator

- type: playTimeTracker
  id: JobPoisk

- type: playTimeTracker
  id: JobPolice

- type: playTimeTracker
  id: JobEcologist

- type: playTimeTracker
  id: JobHeadEcologist

- type: playTimeTracker
  id: JobHeadMilitary

- type: playTimeTracker
  id: JobOfficerMilitary

- type: playTimeTracker
  id: JobHeadBandit

- type: playTimeTracker
  id: JobSci_rector
- type: playTimeTracker
  id: Jobsci_decan
- type: playTimeTracker
  id: JobSci

- type: playTimeTracker
  id: JobStalkerSci

- type: playTimeTracker
  id: JobHeadSeraphims

- type: playTimeTracker
  id: JobMonolith

- type: playTimeTracker
  id: JobUN

- type: playTimeTracker
  id: JobDolg

- type: playTimeTracker
  id: JobHeadDolg

- type: playTimeTracker
  id: JobFreedom

- type: playTimeTracker
  id: JobHeadFreedom

- type: playTimeTracker
  id: JobSBU

- type: playTimeTracker
  id: JobRenegat

- type: playTimeTracker
  id: JobZavetHead

- type: playTimeTracker
  id: JobZavet

- type: playTimeTracker
  id: JobStalkerMercenary

- type: playTimeTracker
  id: JobStalkerHeadMercenary

- type: playTimeTracker
  id: JobStalkerClown

- type: playTimeTracker
  id: JobGreh

- type: playTimeTracker
  id: JobDeserter

- type: playTimeTracker
  id: JobDeserterHead

- type: playTimeTracker
  id: JobClearSky

- type: playTimeTracker
  id: StalkerClearSkyHead
- type: playTimeTracker
  id: JobJaba

- type: playTimeTracker
  id: JobJabaAce

- type: playTimeTracker
  id: JobMilitia

- type: playTimeTracker
  id: JobMilitiaCommander

- type: playTimeTracker
  id: JobDoctor

- type: playTimeTracker
  id: JobHeadDoctor

- type: playTimeTracker
  id: JobMayorCity

- type: playTimeTracker
  id: JobProkuror

- type: playTimeTracker
  id: JobMagistrate

- type: playTimeTracker
  id: JobPriest

- type: playTimeTracker
  id: JobGuide

- type: playTimeTracker
  id: JobStalkerBartender

# Херувим серафимов
- type: playTimeTracker
  id: JobCherubimSeraphims

# Эволверы и их группировки
- type: playTimeTracker
  id: JobEvolver

- type: playTimeTracker
  id: JobEvolverPackFang

- type: playTimeTracker
  id: JobEvolverPackAlpha

- type: playTimeTracker
  id: JobEvolverSymbioteMedium

- type: playTimeTracker
  id: JobEvolverSymbioteArchon

# Stalker EN

- type: playTimeTracker
  id: JobHeadMonolith
- type: playTimeTracker
  id: JobHeadRenegat
- type: playTimeTracker
  id: JobHeadClearSky
- type: playTimeTracker
  id: JobHeadMilitaryStalker
