- type: job
  id: StalkerClown
  name: job-clown
  icon: clowns
  description: job-clown-desc
  playTimeTracker: JobStalkerClown
  whitelisted: true
  requirements:
  # - !type:RoleTimeRequirement
  #   role: JobStalkerClown
  #   time: 1
  - !type:SpeciesRequirement
    species:
    - Human
    - Dwarf
  startingGear: StalkerClownGear
  supervisors: job-clown-supervisor
  special:
  - !type:AddComponentSpecial
    components:
    - type: Access
      tags:
      - Stalker
      - Circus
    - type: Bands
      band: Stalker
      bandIcon: clowns
    - type: BlockTackingHolyItems
    - type: TeethPull
      teethProto: ToothStalker
      pullingItemTag: PliersStalker
      teethCount: 3
      initialTeeth: 3
    - type: ClownScream
      slot: mask
      sound: /Audio/_Stalker/Effects/CircusMask.ogg
      texture:
        sprite: /Textures/_Stalker/Objects/Clothing/mask/clown_unmask.rsi
        state: void_head

- type: startingGear
  id: StalkerClownGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    mask: ClothingMaskClown
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsWork
