- type: job
  id: StalkerClearSky
  name: job-clearsky
  icon: cn
  description: job-clearsky-desc
  playTimeTracker: JobClearSky
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobClearSky
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerClearSkyGear
  supervisors: job-clearsky-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - CN
      - type: Bands
        altBand: stalker
        canChange: true
        band: Stalker
        bandIcon: cn
        bandProto: STClearSkyBand
        bandRankId: 1
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3
      - type: NpcFactionMember
        factions:
        - ClearSky

- type: job
  id: StalkerHeadClearSky
  name: Clear Sky Commander
  icon: cn
  description: Discover the secrets of the Zone. Reach the center of the Zone no matter what.
  playTimeTracker: JobHeadClearSky
  whitelisted: true
  requirements:
  # - !type:RoleTimeRequirement
  #   role: JobClearSky
  #   time: 1
  - !type:SpeciesRequirement
    species:
    - Human
    - Dwarf
  startingGear: StalkerClearSkyGearHead # EN
  supervisors: I think you're in charge?
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
    - type: Access
      tags:
      - CN
    - type: Bands
      altBand: stalker
      canChange: true
      band: Stalker
      bandIcon: cn
      bandProto: STClearSkyBand
      bandRankId: 2
    - type: BlockTackingHolyItems
    - type: TeethPull
      teethProto: ToothStalker
      pullingItemTag: PliersStalker
      teethCount: 3
      initialTeeth: 3
    - type: NpcFactionMember
      factions:
      - ClearSky

- type: job
  id: StalkerClearSkyHead
  name: job-clearsky-head
  icon: cn
  description: job-clearsky-desc
  playTimeTracker: StalkerClearSkyHead
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobClearSky
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerClearSkyGear
  supervisors: job-clearsky-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - CN
      - type: Bands
        band: Stalker
        bandIcon: cn
        bandProto: STClearSkyBand
        bandRankId: 2
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3


- type: startingGear
  id: StalkerClearSkyGear
  equipment:
    id: ClearSkyPDA
    neck: ClothingNeckDogtagClearSky # EN
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterCoatBomber
    back: ClothingBackpackDuffelBlackStalker

# EN
- type: startingGear
  id: StalkerClearSkyGearHead
  equipment:
    id: ClearSkyPDA
    neck: ClothingNeckDogtagClearSkyLeader
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterCoatBomber
    back: ClothingBackpackDuffelBlackStalker

- type: stBand
  id: STClearSkyBand
  name: Clear Sky
  factionId: ClearSky
  maxMembers: 6
  managingRankId: 2
  hierarchy:
    1: StalkerClearSky
    2: StalkerHeadClearSky
