- type: department
  id: Stalker
  color: "#9FED58"
  name: department-Stalker
  description: department-Stalker-description
  weight: 10
  roles:
  - Stalker
  - StalkerNeutral

# - type: department
#   id: StalkerDisabled
#   description: "department-StalkerAdvanced-description"
#   color: "#9FED58"
#   roles:
#   # - PoliceOfficer
#   # - MayorCity
#   # - Prokuror
#   # - Magistrate
#   # - Priest
#   # - Bartender
#   # - Doctor
#   # - HeadDoctor
#   # - Police
#   # - StalkerSBU
#   # - StalkerZavet
#   # - StalkerProjectOrchestrator
#   # - StalkerProjectPawn
#   # - StalkerJaba
#   # - StalkerJabaAce
#   # - Seraphim
#   # - SeraphimHead
#   # - SeraphimCherubim
#   # - StalkerZavet
#   # - StalkerPostulant
#   # - StalkerBishop
#   # - StalkerClown
#   # - StalkerEcologist
#   # - StalkerHeadEcologist
#   # - StalkerPoisk
#   # - StalkerVeteran
#   # - StalkerGuide
#   # - MilitaryStalker
#   # - HeadMilitaryStalker
#   # - StalkerDeserter
#   # - StalkerDeserterHead

- type: department
  id: StalkerAdvanced
  name: department-StalkerAdvanced
  description: department-StalkerAdvanced-description
  color: "#9FED58"
  weight: 9
  roles:
  - StalkerDolg
  - StalkerHeadDolg
  - StalkerFreedom
  - StalkerHeadFreedom
  - StalkerClearSky
  - StalkerHeadClearSky
  - StalkerJournalist

- type: department
  id: StalkerBrigands
  name: department-StalkerBrigands
  description: department-StalkerBrigands-description
  color: "#111111"
  weight: 8
  roles:
  - StalkerBandit
  - StalkerHeadBandit
  - StalkerMercenary
  - StalkerHeadMercenary
  - StalkerRene
  - StalkerHeadRene

- type: department
  id: StalkerOfficials
  name: department-StalkerOfficials
  description: department-StalkerOfficials-description
  color: "#0000FF"
  weight: 7
  roles:
  - Military
  - MilitaryOfficer
  - MilitaryHead

- type: department
  id: StalkerUnitedNations
  name: department-StalkerUnitedNations
  description: department-StalkerUnitedNations-description
  color: "#0000FF"
  weight: 6
  roles:
  - StalkerUN
# - StalkerUNISG

- type: department
  id: StalkerReligius
  name: department-StalkerReligius
  description: department-StalkerReligius-description
  color: "#C0C0C0"
  weight: 5
  roles:
  - StalkerMonolith
  - StalkerHeadMonolith
  - StalkerGreh
  - StalkerPostulant
  - StalkerBishop
