- type: job
  id: StalkerScientist
  name: job-scientist
  icon: sci
  description: job-scientist-desc
  playTimeTracker: JobStalkerSci
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerSci
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear
  supervisors: job-scientist-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Sci
      - type: Bands
        band: Stalker
        bandIcon: sci
        bandProto: STSciBand
        bandRankId: 2
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3
      - type: NpcFactionMember
        factions:
        - Sci

- type: job
  id: sci
  name: job-sci
  icon: sci
  description: job-sci-desc
  playTimeTracker: JobSci
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobSci
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear
  supervisors: job-scientist-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Sci
      - type: Bands
        band: Stalker
        bandIcon: ecologists
        bandProto: STSciBand
        bandRankId: 2
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3
      - type: NpcFactionMember
        factions:
        - Sci

- type: job
  id: sci_decan
  name: job-sci_decan
  icon: sci
  description: job-sci_decan-desc
  playTimeTracker: Jobsci_decan
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: Jobsci_decan
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGearHead
  supervisors: job-scientist-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Sci
      - type: Bands
        band: Stalker
        bandIcon: sci_decan
        bandProto: STSciBand # Stalker-TODO: Before it was "STSciDecanBand" but it was commented. Read the reason in below comment.
        bandRankId: 2
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3
      - type: NpcFactionMember
        factions:
        - Sci

- type: job
  id: sci_rector
  name: job-sci_rector
  icon: sci
  description: job-sci_rector-desc
  playTimeTracker: JobSci_rector
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobSci_rector
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear3
  supervisors: job-scientist-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - SciHead
        - type: Bands
          band: Stalker
          bandIcon: sci_rector
          bandProto: STSciBand # Stalker-TODO: Before it was "STSciRectorBand" but it was commented. Read the reason in below comment.
          bandRankId: 3
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3
        - type: NpcFactionMember
          factions:
          - Sci

- type: startingGear
  id: SciGear
  equipment:
    id: ScientistPDA
    neck: ClothingNeckDogtagEco # EN
    legs: ClothingLegsJeansSandCargo
    shoes: STClothingShoesBootsCombatFilled
    torso: ClothingTorsoShirtWhiteScientific
    outerClothing: ClothingOuterJacketSCI
    gloves: ClothingHandsGlovesNitrile

# EN
- type: startingGear
  id: SciGearHead
  equipment:
    id: ScientistPDA
    neck: ClothingNeckDogtagEcoLeader # EN
    legs: ClothingLegsJeansSandCargo
    shoes: STClothingShoesBootsCombatFilled
    torso: ClothingTorsoShirtWhiteScientific

- type: stBand
  id: STSciBand
  name: Scientists
  factionId: Scientists
  maxMembers: 6
  managingRankId: 3
  hierarchy:
    1: StalkerScientist


- type: startingGear
  id: SciGear2
  equipment:
    id: ScientistPDA
    legs: ClothingLegsJeansSandCargo
    shoes: STClothingShoesBootsCombatFilled
    torso: ClothingTorsoShirtWhiteScientific
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    head: ClothingHeadHatBeretRND
    gloves: ClothingHandsGlovesNitrile

# - type: stBand # Stalker-TODO: Why not combine them all under "STSciBand" band prototype? Also, factionId "ScientistsDecan" does not exist!
  # id: STSciDecanBand
  # name: ScientistsDecan
  # factionId: ScientistsDecan
  # maxMembers: 20
  # managingRankId: 3
  # hierarchy:
     # 1: sci_decan


- type: startingGear
  id: SciGear3
  equipment:
    id: ScientistPDA
    legs: ClothingLegsJeansSandCargo
    shoes: STClothingShoesBootsCombatFilled
    torso: ClothingTorsoShirtWhiteScientific
    outerClothing: ClothingOuterCoatRD
    head: ClothingHeadBeretUN
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesNitrile

# - type: stBand # Stalker-TODO: Why not combine them all under "STSciBand" band prototype? Also, factionId "ScientistsRector" does not exist!
  # id: STSciRectorBand
  # name: ScientistsRector
  # factionId: ScientistsRector
  # maxMembers: 20
  # managingRankId: 3
  # hierarchy:
    # 1: sci_rector
