- type: job
  id: MayorCity
  name: job-mayor-city
  icon: grajdansksprite
  description: job-mayor-city-desc
  playTimeTracker: JobMayorCity
  requirements:
    - !type:RoleTimeRequirement
      role: JobMayorCity
      time: 1
  startingGear: MayorCityGear
  supervisors: job-mayor-city-supervisor
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - MayorCity
          - Prokuror
          - Magistrate
          - Priest
          - Barthender
      - type: Bands
        band: Stalker
        bandIcon: grajdansksprite
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3


- type: job
  id: Prokuror
  name: job-prokuror
  icon: grajdansksprite
  description: job-prokuror-desc
  playTimeTracker: JobProkuror
  requirements:
    - !type:RoleTimeRequirement
      role: JobProkuror
      time: 1
  startingGear: ProkurorGear
  supervisors: job-supervisor-mayor
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Prokuror
        - type: Bands
          band: Stalker
          bandIcon: grajdansksprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: job
  id: Magistrate
  name: job-magistrate
  icon: grajdansksprite
  description: job-magistrate-desc
  playTimeTracker: JobMagistrate
  requirements:
    - !type:RoleTimeRequirement
      role: JobMagistrate
      time: 1
  startingGear: MagistrateGear
  supervisors: job-supervisor-mayor
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Magistrate
        - type: Bands
          band: Stalker
          bandIcon: grajdansksprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: job
  id: Priest
  name: job-priest
  icon: grajdansksprite
  description: job-priest-desc
  playTimeTracker: JobPriest
  requirements:
    - !type:RoleTimeRequirement
      role: JobPriest
      time: 1
  startingGear: PriestGear
  supervisors: job-supervisor-mayor
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Priest
        - type: Bands
          band: Stalker
          bandIcon: grajdansksprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: job
  id: StalkerBartender
  name: job-stalker-bartender
  icon: grajdansksprite
  description: job-stalker-bartender-desc
  playTimeTracker: JobStalkerBartender
  requirements:
    - !type:RoleTimeRequirement
      role: JobStalkerBartender
      time: 1
  startingGear: StalkerBartenderGear
  supervisors: job-supervisor-mayor
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Barthender
        - type: Bands
          band: Stalker
          bandIcon: grajdansksprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: startingGear
  id: MayorCityGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen

- type: startingGear
  id: ProkurorGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen

- type: startingGear
  id: MagistrateGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen

- type: startingGear
  id: PriestGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen

- type: startingGear
  id: StalkerBartenderGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen
