- type: job
  id: Doctor
  name: job-doctor
  icon: medbeysprite
  description: job-doctor-desc
  playTimeTracker: JobDoctor
  requirements:
    - !type:RoleTimeRequirement
      role: JobDoctor
      time: 1
  startingGear: DoctorStalkerGear
  supervisors: job-doctor-supervisor
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Doctor
        - type: Bands
          band: Stalker
          bandIcon: medbeysprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: job
  id: HeadDoctor
  name: job-head-doctor
  icon: medbeysprite
  description: job-head-doctor-desc
  playTimeTracker: JobHeadDoctor
  requirements:
    - !type:RoleTimeRequirement
      role: JobHeadDoctor
      time: 1
  startingGear: DoctorStalkerGear
  supervisors: job-head-doctor-supervisor
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - HeadDoctor
        - type: Bands
          band: Stalker
          bandIcon: medbeysprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: startingGear
  id: DoctorStalkerGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesColorWhite
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen
    outerClothing: ClothingOuterCoatLab
    back: ClothingBackpackDuffelMedicalStalker
